const baseActionButtonStyles = {
    width: "32px",
    height: "32px",
    borderRadius: "999px",
    border: "1px solid #d6dbe5",
    background: "#fff",
    color: "#4b5563",
    fontSize: "10px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
};

const addEditEventStyles = {
    headerStyles: {
        marginBottom: "22px",
    },
    formStyles: {
        background: "transparent",
    },
    textareaStyles: {
        height: "96px",
        borderRadius: "18px",
        padding: "12px 16px",
        resize: "none",
    },
    actionsStyles: {
        marginTop: "6px",
    },
    outlineButtonStyles: {
        borderRadius: "999px",
        border: "1px solid #e6e9ef",
        background: "#fff",
        padding: "8px 22px",
        fontSize: "13px",
        fontWeight: 600,
        color: "#2f343a",
        cursor: "pointer",
    },
    parentStyles: {
        marginBottom: "18px",
    },
    parentTitleStyles: {
        fontSize: "16px",
        fontWeight: 700,
        color: "#1f2a8a",
        marginBottom: "6px",
    },
    parentMetaStyles: {
        fontSize: "12px",
        color: "#7280a7",
        display: "flex",
        flexWrap: "wrap",
        gap: "8px",
        alignItems: "center",
    },
    dotStyles: {
        width: "2px",
        height: "14px",
        background: "#c7d2fe",
    },
    subEventListStyles: {
        display: "flex",
        flexDirection: "column",
        gap: "8px",
        marginBottom: "12px",
    },
    subEventCardStyles: {
        display: "flex",
        alignItems: "stretch",
        justifyContent: "space-between",
        gap: "10px",
        padding: "8px 10px",
        border: "1px solid #edf1f8",
        borderRadius: "14px",
        background: "#fff",
        boxShadow: "0 4px 12px rgba(15, 23, 42, 0.04)",
        flexWrap: "wrap",
    },
    subEventDateBadgeStyles: {
        width: "72px",
        minWidth: "72px",
        borderRadius: "10px",
        background: "#eaf0ff",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: "1px",
        padding: "6px 4px",
    },
    subEventDateTimeStyles: {
        fontSize: "9px",
        color: "#4b5563",
        fontWeight: 600,
        lineHeight: 1.3,
        textAlign: "center",
    },
    subEventDateDayStyles: {
        fontSize: "clamp(16px, 1.5vw, 26px)",
        lineHeight: 1,
        fontWeight: 700,
        color: "#1f2a8a",
    },
    subEventDateMonthStyles: {
        fontSize: "clamp(11px, 1vw, 16px)",
        fontWeight: 700,
        color: "#1f2a8a",
        lineHeight: 1.1,
        textTransform: "capitalize",
    },
    subEventMainStyles: {
        flex: "1 1 220px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        gap: "4px",
        minWidth: 0,
    },
    subEventTitleStyles: {
        fontSize: "clamp(13px, 1.2vw, 20px)",
        fontWeight: 700,
        color: "#1f2a8a",
        lineHeight: 1.15,
    },
    subEventMetaStyles: {
        fontSize: "clamp(10px, 0.8vw, 12px)",
        color: "#6b7280",
        fontWeight: 600,
        display: "flex",
        flexWrap: "wrap",
        alignItems: "center",
        gap: "4px",
    },
    subEventDescriptionStyles: {
        fontSize: "clamp(10px, 0.75vw, 12px)",
        lineHeight: 1.35,
        color: "#7a828c",
    },
    subEventActionsStyles: {
        display: "flex",
        alignItems: "center",
        gap: "6px",
        alignSelf: "flex-start",
        marginLeft: "auto",
    },
    subEventActionButtonStyles: baseActionButtonStyles,
    subEventRemoveStyles: {
        ...baseActionButtonStyles,
        border: "1px solid #ef4444",
        color: "#ef4444",
    },
};

export default addEditEventStyles;
